FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

RUN pip install confluent-kafka pandas sqlalchemy psycopg2-binary pyyaml

COPY dmp_processor.py .
COPY ddl_config.yaml .

CMD ["python", "dmp_processor.py"]
